
# ????????????
spring:
  application:
    name: my-demo-app
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/default_db?useSSL=false
#    username: root
#    password: 123456
#  redis:
#    host: localhost
#    port: 6379
  config:
    activate:
      on-profile: dev

  aop:
    proxy-target-class: false
